# Generated by Django 5.0.1 on 2024-01-13 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coreapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Save_Forms',
            new_name='User',
        ),
    ]
