# Generated by Django 4.2.7 on 2023-12-03 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Enroll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stid', models.IntegerField()),
                ('name', models.CharField(max_length=70)),
                ('department', models.CharField(max_length=20)),
                ('address', models.TextField(max_length=70)),
                ('email_address', models.EmailField(max_length=40)),
                ('phone_number', models.TextField(max_length=19, verbose_name='+88 ')),
            ],
        ),
    ]
