# Generated by Django 4.2.7 on 2023-12-03 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enroll', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enroll',
            name='phone_number',
            field=models.TextField(max_length=19),
        ),
    ]
