# Generated by Django 4.2.8 on 2023-12-04 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stuname', models.CharField(max_length=40)),
                ('stuemail', models.EmailField(max_length=40)),
                ('stupass', models.CharField(max_length=40)),
            ],
        ),
    ]
