# Generated by Django 4.2.7 on 2023-12-02 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enroll', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='comments',
            field=models.TextField(default='not available', max_length=40),
        ),
    ]
